import type { Seller, Listing } from '../types/ewmart';

const now = Date.now();
const DAY = 24 * 60 * 60 * 1000;
const HOUR = 60 * 60 * 1000;

export const INITIAL_SELLERS: Seller[] = [
  {
    id: "sel_1",
    name: "Tanvir Ahmed",
    email: "2023-1-60-045@ewubd.edu",
    studentId: "2023-1-60-045",
    department: "CSE",
    whatsapp: "+8801712345678",
    facebookUrl: "https://facebook.com/tanvir.ewu",
    instagramUrl: "https://instagram.com/tanvir_ahmed",
    bio: "3rd year CSE student selling text books and lab gear.",
    meetupSpots: ["Library", "Cafeteria", "Ground Floor Plaza"],
    status: "approved",
    agreedToPolicyAt: now - 30 * DAY,
    createdAt: now - 30 * DAY
  },
  {
    id: "sel_2",
    name: "Nusrat Jahan",
    email: "2024-1-70-089@ewubd.edu",
    studentId: "2024-1-70-089",
    department: "Pharmacy",
    whatsapp: "+8801819283746",
    facebookUrl: "https://facebook.com/nusrat.pharmacy",
    bio: "Pharmacy major. Clean lab equipment & study notes.",
    meetupSpots: ["Cafeteria", "Gate 2"],
    status: "approved",
    agreedToPolicyAt: now - 20 * DAY,
    createdAt: now - 20 * DAY
  },
  {
    id: "sel_3",
    name: "Rafiul Islam",
    email: "2022-2-10-112@ewubd.edu",
    studentId: "2022-2-10-112",
    department: "BBA",
    whatsapp: "+8801911223344",
    bio: "BBA senior clearing out course packs & electronics.",
    meetupSpots: ["Ground Floor Plaza", "Main Gate"],
    status: "approved",
    agreedToPolicyAt: now - 45 * DAY,
    createdAt: now - 45 * DAY
  },
  {
    id: "sel_4",
    name: "Sadia Rahman",
    email: "2023-3-50-201@ewubd.edu",
    studentId: "2023-3-50-201",
    department: "EEE",
    whatsapp: "+8801677889900",
    bio: "EEE project builder & components reseller.",
    meetupSpots: ["Library", "Student Lounge"],
    status: "pending",
    agreedToPolicyAt: now - 2 * DAY,
    createdAt: now - 2 * DAY
  },
  {
    id: "sel_5",
    name: "Tasnim Akter",
    email: "2024-2-40-108@ewubd.edu",
    studentId: "2024-2-40-108",
    department: "Economics",
    whatsapp: "+8801555667788",
    bio: "Eco sophomore selling original printed reference manuals.",
    meetupSpots: ["Cafeteria", "Auditorium Lobby"],
    status: "pending",
    agreedToPolicyAt: now - 1 * DAY,
    createdAt: now - 1 * DAY
  },
  {
    id: "sel_6",
    name: "Kamrul Hasan",
    email: "2020-1-30-999@ewubd.edu",
    studentId: "2020-1-30-999",
    department: "English",
    whatsapp: "+8801300112233",
    bio: "Ex-student account.",
    meetupSpots: ["Gate 2"],
    status: "banned",
    banReason: "Reported for listing prohibited non-authentic academic exam solutions",
    bannedAt: now - 5 * DAY,
    agreedToPolicyAt: now - 60 * DAY,
    createdAt: now - 60 * DAY
  },
  {
    id: "sel_7",
    name: "Mahir Faisal",
    email: "2022-1-60-310@ewubd.edu",
    studentId: "2022-1-60-310",
    department: "CSE",
    whatsapp: "+8801744556677",
    facebookUrl: "https://facebook.com/mahir.faisal",
    bio: "Tech enthusiast selling gadgets and design equipment.",
    meetupSpots: ["Ground Floor Plaza", "Library"],
    status: "approved",
    agreedToPolicyAt: now - 15 * DAY,
    createdAt: now - 15 * DAY
  }
];

export const INITIAL_LISTINGS: Listing[] = [
  {
    id: "lst_101",
    sellerId: "sel_1",
    sellerName: "Tanvir Ahmed",
    sellerWhatsapp: "+8801712345678",
    title: "CSE207 Data Structures (Seymour Lipschutz) - Like New",
    description: "Original Schaum Outline Data Structures textbook. Clean pages with minimal pencil highlights. Essential for EWU CSE 207 course.",
    priceBDT: 350,
    category: "textbooks",
    condition: "Used",
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80"],
    meetupSpot: "Library",
    status: "available",
    flagged: false,
    createdAt: now - 3 * HOUR
  },
  {
    id: "lst_102",
    sellerId: "sel_2",
    sellerName: "Nusrat Jahan",
    sellerWhatsapp: "+8801819283746",
    title: "EWU Pharmacy Lab Coat (Size L) & Safety Goggles",
    description: "Official white cotton lab coat with EWU logo patch. Includes anti-scratch polycarbonate lab safety goggles. Used for one semester.",
    priceBDT: 450,
    category: "thrift",
    condition: "Used",
    images: ["https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?w=600&auto=format&fit=crop&q=80"],
    meetupSpot: "Cafeteria",
    status: "available",
    flagged: false,
    createdAt: now - 5 * HOUR
  },
  {
    id: "lst_103",
    sellerId: "sel_1",
    sellerName: "Tanvir Ahmed",
    sellerWhatsapp: "+8801712345678",
    title: "Casio fx-991EX ClassWiz Scientific Calculator",
    description: "Original Casio fx-991EX ClassWiz. Ideal for EEE, CSE, and MAT courses. Fully working solar & battery dual power.",
    priceBDT: 1800,
    category: "electronics",
    condition: "Used",
    images: ["https://images.unsplash.com/photo-1611125832047-1d7ad1e8e48a?w=600&auto=format&fit=crop&q=80"],
    meetupSpot: "Ground Floor Plaza",
    status: "available",
    flagged: false,
    createdAt: now - 1 * DAY
  },
  {
    id: "lst_104",
    sellerId: "sel_3",
    sellerName: "Rafiul Islam",
    sellerWhatsapp: "+8801911223344",
    title: "EWU Cafeteria 5-Day Meal Discount Vouchers",
    description: "Pre-purchased meal tokens for EWU Ground Floor Cafeteria. Valid until end of Fall semester.",
    priceBDT: 480,
    category: "cafeteria",
    condition: "New",
    images: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&auto=format&fit=crop&q=80"],
    meetupSpot: "Ground Floor Plaza",
    status: "reserved",
    flagged: false,
    createdAt: now - 1 * DAY - 4 * HOUR
  },
  {
    id: "lst_105",
    sellerId: "sel_6",
    sellerName: "Kamrul Hasan",
    sellerWhatsapp: "+8801300112233",
    title: "Unauthorized Midterm Exam Solution Cheatsheet Bundle",
    description: "Leaked midterm question patterns and solution notes for ENG101 & ECO101.",
    priceBDT: 1200,
    category: "services",
    condition: "New print",
    images: ["https://images.unsplash.com/photo-1455390582262-044cdead277a?w=600&auto=format&fit=crop&q=80"],
    meetupSpot: "Gate 2",
    status: "available",
    flagged: true,
    flagReason: "Academic dishonesty violation: Leaked exam material reported by 4 students",
    flaggedAt: now - 2 * DAY,
    createdAt: now - 3 * DAY
  },
  {
    id: "lst_106",
    sellerId: "sel_7",
    sellerName: "Mahir Faisal",
    sellerWhatsapp: "+8801744556677",
    title: "Wacom One Graphics Drawing Tablet for Design & Math",
    description: "Wacom One Small tablet with pressure-sensitive pen. Perfect for online board work, math problem solving, and digital art.",
    priceBDT: 4200,
    category: "electronics",
    condition: "Used",
    images: ["https://images.unsplash.com/photo-1526406915894-7bcd65f60845?w=600&auto=format&fit=crop&q=80"],
    meetupSpot: "Library",
    status: "available",
    flagged: false,
    createdAt: now - 2 * DAY - 6 * HOUR
  },
  {
    id: "lst_107",
    sellerId: "sel_2",
    sellerName: "Nusrat Jahan",
    sellerWhatsapp: "+8801819283746",
    title: "MAT101 Differential Calculus (Anton Bivens Davis 10th Ed)",
    description: "Freshly printed and spiral bound edition of Calculus 10th edition. Clean margins, no ink smudges.",
    priceBDT: 280,
    category: "textbooks",
    condition: "New print",
    images: ["https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600&auto=format&fit=crop&q=80"],
    meetupSpot: "Cafeteria",
    status: "available",
    flagged: false,
    createdAt: now - 3 * DAY - 2 * HOUR
  },
  {
    id: "lst_108",
    sellerId: "sel_3",
    sellerName: "Rafiul Islam",
    sellerWhatsapp: "+8801911223344",
    title: "Logitech K380 Multi-Device Bluetooth Wireless Keyboard",
    description: "Compact dark grey Bluetooth keyboard. Works with laptops, tablets, and phones. Great for typing notes in EWU library.",
    priceBDT: 2100,
    category: "electronics",
    condition: "Used",
    images: ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80"],
    meetupSpot: "Main Gate",
    status: "available",
    flagged: false,
    createdAt: now - 4 * DAY
  },
  {
    id: "lst_109",
    sellerId: "sel_7",
    sellerName: "Mahir Faisal",
    sellerWhatsapp: "+8801744556677",
    title: "Custom C/C++ & Python Debugging & Tutoring Service",
    description: "1-on-1 coding assignment guidance and lab logic troubleshooting by senior CSE student. 1 hour session at EWU library study area.",
    priceBDT: 500,
    category: "services",
    condition: "New",
    images: ["https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&auto=format&fit=crop&q=80"],
    meetupSpot: "Library",
    status: "available",
    flagged: false,
    createdAt: now - 4 * DAY - 5 * HOUR
  },
  {
    id: "lst_110",
    sellerId: "sel_1",
    sellerName: "Tanvir Ahmed",
    sellerWhatsapp: "+8801712345678",
    title: "Arduino Uno R3 Starter Kit with Sensors & Breadboard",
    description: "Complete electronics project kit: Arduino Uno board, breadboard, jumper wires, LEDs, ultrasonic sensor, and servo motor. Used for CSE303 project.",
    priceBDT: 1450,
    category: "electronics",
    condition: "Used",
    images: ["https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?w=600&auto=format&fit=crop&q=80"],
    meetupSpot: "Ground Floor Plaza",
    status: "sold",
    flagged: false,
    createdAt: now - 5 * DAY
  },
  {
    id: "lst_111",
    sellerId: "sel_3",
    sellerName: "Rafiul Islam",
    sellerWhatsapp: "+8801911223344",
    title: "EWU Official Navy Blue Hoodie (Winter Collection - Size XL)",
    description: "Warm navy blue EWU campus hoodie with fleece lining. Worn only a few times last winter.",
    priceBDT: 650,
    category: "thrift",
    condition: "Used",
    images: ["https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&auto=format&fit=crop&q=80"],
    meetupSpot: "Ground Floor Plaza",
    status: "available",
    flagged: false,
    createdAt: now - 6 * DAY
  },
  {
    id: "lst_112",
    sellerId: "sel_7",
    sellerName: "Mahir Faisal",
    sellerWhatsapp: "+8801744556677",
    title: "Spam Promotional Wireless Earbuds (Fake Brand)",
    description: "Counterfeit branded Bluetooth earbuds offered at suspicious low price.",
    priceBDT: 300,
    category: "electronics",
    condition: "New",
    images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80"],
    meetupSpot: "Gate 2",
    status: "available",
    flagged: true,
    flagReason: "Reported as counterfeit / misleading item listing by campus buyers",
    flaggedAt: now - 1 * DAY,
    createdAt: now - 2 * DAY
  },
  {
    id: "lst_113",
    sellerId: "sel_2",
    sellerName: "Nusrat Jahan",
    sellerWhatsapp: "+8801819283746",
    title: "Principles of Marketing (Kotler & Armstrong 17th Ed)",
    description: "Essential reference textbook for EWU BBA & Pharmacy management electives. Includes clean index notes.",
    priceBDT: 400,
    category: "textbooks",
    condition: "Used",
    images: ["https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&auto=format&fit=crop&q=80"],
    meetupSpot: "Cafeteria",
    status: "available",
    flagged: false,
    createdAt: now - 7 * DAY
  },
  {
    id: "lst_114",
    sellerId: "sel_1",
    sellerName: "Tanvir Ahmed",
    sellerWhatsapp: "+8801712345678",
    title: "Anker Soundcore Select 2 Portable Bluetooth Speaker",
    description: "16W stereo sound, IPX7 waterproof. Excellent battery backup. Includes Type-C charging cable.",
    priceBDT: 2600,
    category: "electronics",
    condition: "Used",
    images: ["https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80"],
    meetupSpot: "Library",
    status: "available",
    flagged: false,
    createdAt: now - 8 * DAY
  },
  {
    id: "lst_115",
    sellerId: "sel_3",
    sellerName: "Rafiul Islam",
    sellerWhatsapp: "+8801911223344",
    title: "Figma & React UI Development Mentorship Session",
    description: "Hands-on guidance for building web projects, portfolio creation, and Git version control basics.",
    priceBDT: 600,
    category: "services",
    condition: "New",
    images: ["https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&auto=format&fit=crop&q=80"],
    meetupSpot: "Ground Floor Plaza",
    status: "available",
    flagged: false,
    createdAt: now - 9 * DAY
  }
];
